### ISSUE TITLE
Problem with this benchmark

### ISSUE THREAD

**Issue by wjakob** [terib0l/faster-python#1]
Dear @terib0l,

I saw this repository cross-referenced to the nanobind one.

There is a fatal flaw in your benchmark. You are compiling the C++ code with optimizations disabled (which is the default in CMake). Add the following to `CMakeLists.txt` to make a release build the default (or call `cmake with -DCMAKE_BUILD_TYPE=Release`).

```
   if (NOT CMAKE_BUILD_TYPE AND NOT CMAKE_CONFIGURATION_TYPES)
     set(CMAKE_BUILD_TYPE Release CACHE STRING "Choose the type of build." FORCE)
     set_property(CACHE CMAKE_BUILD_TYPE PROPERTY STRINGS "Debug" "Release" "MinSizeRel" "RelWithDebInfo")
   endif()
```

**Comment by terib0l** [comment]
Dear @wjakob 

Thank you for offering your valuable advice!
I've modified that part, and nanobind has gotten certainly faster.

**Comment by wjakob** [comment]
Great! To understand the remaining difference, you might want to look at the disassembly. There is no reason why Rust should be faster than C++ in such a simple example. Likely Rust still has more optimizations enabled (e.g. by optimizing specifically for the host processor, which Clang/GCC do not do by default).
